
```{r}
library(raster)
library(maptools)
library(rgdal)
library(rgeos)
library(RCurl)
library(devtools)
library(rasterVis)
library(gdalUtils)
```

```{r}
b3 <- raster("C:/Users/gusta/Desktop/PhD/Classes/ENVE152/final/LC08_L2SP_043034_20171216_20200902_02_T1_SR_B3.TIF")
   
b6 <- raster("C:/Users/gusta/Desktop/PhD/Classes/ENVE152/final/LC08_L2SP_043034_20171216_20200902_02_T1_SR_B6.TIF")


mndwi <- (b3 - b6)/(b3 + b6)

DonPedro_dec_2017 <- calc(mndwi, function(x){x[x > 0] <- NA;return(x)})

cuts=c(-1, 0, 1)
pal= colorRampPalette(c("white", "black"))
plot(DonPedro_dec_2017, breaks=cuts, col=pal(2), main= "NDWI Dec 2017")
#writeRaster(mndwi_dec2017, datatype="FLT4S", filename = "raster\\water_ndwi_dec2017.tif", format = "GTiff", overwrite=TRUE)
```




```{r}
donpedro <- shapefile("C:/Users/gusta/Desktop/PhD/Classes/ENVE152/final/DonPedro.shp")
#acbuf <- gBuffer(donpedro, width = 500, quadsegs=100) 
#donpedro2 <- crop(donpedro, acbuf)
donpedro <- gBuffer(donpedro3, width= 500, byid = FALSE)
donpedro3 <- spTransform(donpedro, crs(mndwi))

macalt <- mask(mndwi, donpedro3)

DonPedro_dec_2017 <- calc(macalt, function(x){x[x < 0] <- NA;return(x)})

plot(macalt_dec_2017, xlim=c(715000,745000), ylim=c(4120000,4150000), xaxs="i", yaxs="i")
#plot(gBuffer(donpedro3, width= 500, byid = FALSE), add=T)#, border='blue', add= T)
dev.off()#, breaks=cuts, col=pal(2), main= "NDWI Dec 2017")
```


```{r}

mapview::mapview(DonPedro_dec_2017)
```


```{r}
## Load packages
library(getSpatialData)
library(raster)
library(sf)
library(sp)

## Define time range and platform
time_range <-  c("2017-12-01", "2017-12-31")
platform <- "Sentinel-2"

## set login credentials and an archive directory
# }
# NOT RUN {
login_CopHub(username = "gustavo.facincani") #asks for password or define 'password'
set_archive("C:/Users/gusta/Desktop/PhD/Classes/ENVE152/final")

## Use getSentinel_query to search for data (using the session AOI)
records <- getSentinel_query(time_range = time_range, platform = platform)

## Get an overview of the records
View(records) #get an overview about the search records
colnames(records) #see all available filter attributes
unique(records$processinglevel) #use one of the, e.g. to see available processing levels

## Filter the records
records_filtered <- records[which(records$processinglevel == "Level-1C"),] #filter by Level

## Preview a single record
getSentinel_preview(record = records_filtered[5,])
```

## Download some datasets
datasets <- getSentinel_data(records = records_filtered[c(4,5,6),])

## Make them ready to use
datasets_prep <- prepSentinel(datasets, format = "tiff")

## Load them to R
r <- stack(datasets_prep[[1]][[1]][1]) #first dataset, first tile, 10m resoultion

````
