---
title: "Storage_GCMs"
author: "Gustavo Facincani Dourado"
date: "6/14/2020"
output: html_document
---

```{r}
Livneh_Stor_Mer <- read_csv("C:/Users/gusta/Box/VICE Lab/RESEARCH/PROJECTS/CERC-WET/Task7_San_Joaquin_Model/Pywr models/results/Binary IFRs x Prices/merced/historical/Livneh/Reservoir_Storage_mcm.csv")[-c(1:3), c(1,7)] %>%
 mutate(node = as.Date(node, format = "%Y-%m-%d"),
           `Livneh (Historical)` = as.numeric(`Lake McClure_1`)) %>%
    filter(between(node, as.Date("1980-10-01"), as.Date("2010-09-30")))
Livneh_Stor_Mer

CanES_Stor_Mer <- read_csv("C:/Users/gusta/Box/VICE Lab/RESEARCH/PROJECTS/CERC-WET/Task7_San_Joaquin_Model/Pywr models/results/Binary IFRs x Prices/merced/gcms/CanESM2_rcp85/Reservoir_Storage_mcm.csv")[-c(1:3), c(1,7)] %>%
 mutate(node = as.Date(node, format = "%Y-%m-%d"),
           `CanESM2` = as.numeric(`Lake McClure_1`))
CanES_Stor_Mer

CNRM_Stor_Mer <- read_csv("C:/Users/gusta/Box/VICE Lab/RESEARCH/PROJECTS/CERC-WET/Task7_San_Joaquin_Model/Pywr models/results/Binary IFRs x Prices/merced/gcms/CNRM-CM5_rcp85/Reservoir_Storage_mcm.csv")[-c(1:3), c(1,7)] %>%
 mutate(node = as.Date(node, format = "%Y-%m-%d"),
           `CNRM-CM5` = as.numeric(`Lake McClure_1`))
CNRM_Stor_Mer


HadGEM_Stor_Mer <- read_csv("C:/Users/gusta/Box/VICE Lab/RESEARCH/PROJECTS/CERC-WET/Task7_San_Joaquin_Model/Pywr models/results/Binary IFRs x Prices/merced/gcms/HadGEM2-ES_rcp85/Reservoir_Storage_mcm.csv")[-c(1:3), c(1,7)] %>%
 mutate(node = as.Date(node, format = "%Y-%m-%d"),
           `HadGEM2-ES` = as.numeric(`Lake McClure_1`))
HadGEM_Stor_Mer


MIROC_Stor_Mer <- read_csv("C:/Users/gusta/Box/VICE Lab/RESEARCH/PROJECTS/CERC-WET/Task7_San_Joaquin_Model/Pywr models/results/Binary IFRs x Prices/merced/gcms/MIROC5_rcp85/Reservoir_Storage_mcm.csv")[-c(1:3), c(1,7)] %>%
 mutate(node = as.Date(node, format = "%Y-%m-%d"),
           MIROC5 = as.numeric(`Lake McClure_1`))
MIROC_Stor_Mer

```




```{r}
Livneh_Mer_Stor1 <- Livneh_Stor_Mer[(-2)] 
Livneh_Mer_Stor1 <- melt(Livneh_Mer_Stor1, id = "node")
Livneh_Mer_Stor1


Stor_Mer <- cbind(CanES_Stor_Mer[(-2)], CNRM_Stor_Mer[(-2)], 
                HadGEM_Stor_Mer[(-2)], MIROC_Stor_Mer[(-2)])
 

Stor_Mer1 <- melt(Stor_Mer, id = "node")
Stor_Mer1
```

```{r}
#Total capacity is 1238.6 mcm, 142 mcm is dead pool, so 1/3 of it is 365.533 

OperCap_McClure <- rbind(Stor_Mer1, Livneh_Mer_Stor1) %>%
  mutate(Month = as.factor(format(as.Date(node, format = "%B"), "%b")),
                           Year = water_year(node, origin = "usgs"),
         Scenario = as.factor("RCP 8.5"),
         DeadPool = as.numeric(142),
         OperatingCapacity = (value - DeadPool),
         Count = ifelse(OperatingCapacity > 365.533, 0,1))

OperCap_McClure$GCM <- OperCap_McClure$variable
OperCap_McClure$variable <- as.factor("Lake McClure")
OperCap_McClure

OperCap_McClure$GCM <- factor(OperCap_McClure$GCM, levels = c("Livneh (Historical)","HadGEM2-ES", "CanESM2", "MIROC5", "CNRM-CM5"))

```


```{r}
Stor_Mer2 <- rbind(Stor_Mer1, Livneh_Mer_Stor1) %>%
  mutate(Month = as.factor(format(as.Date(node, format = "%B"), "%b")),
                           Year = water_year(node, origin = "usgs"),
         Scenario = as.factor("RCP 8.5")) %>%
group_by(Year, Month, variable) %>%
   dplyr::summarize(MonthlyTotal = sum(value))

  

Stor_Mer2$variable <- factor(Stor_Mer2$variable, levels = c("Livneh (Historical)", "HadGEM2-ES", "CanESM2", "MIROC5", "CNRM-CM5")) 

Stor_Mer3 <- Stor_Mer2 %>%
  group_by(Year, variable) %>%
   dplyr::summarize(AnnualTotal = sum(MonthlyTotal)) 

Stor_Mer3
```



```{r}
ggplot(Stor_Mer2) + 
  theme_bw(base_size=12, base_family='Times New Roman') + #change font to Times New Roman, 12pt, Bold
    geom_boxplot(aes( x = Month, y = MonthlyTotal, fill = variable), outlier.alpha = 0.3) + #plot monthly observed data in greenish blue
   #geom_line(aes(x = node, y = value)) +
    scale_y_continuous(limits = c(0, NA),
                      expand = c(0, NA),
                      labels = comma) +
    scale_x_discrete(limits=c("Oct","Nov","Dec", "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep"))+
  scale_fill_manual(values = c("#5A5A5A", "#E69F00", "#F0E442", "#009E73", "#56B4E9")) +

  labs(fill = "RCP 8.5",
       title = "Merced River",
    x = element_blank(), 
       y = "Total Storage (mcm/month)") + #name of x axis
  theme(legend.position = "bottom",
        legend.direction = "horizontal",
        legend.box.margin = margin(t = -17),
        plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5),
        strip.placement = "outside",
        strip.background = element_blank(),
        panel.spacing.y = unit(0, "lines"))+
  png("Mer_storage_GCMs.png", units ="in", width=8, height=5, res = 300)

```

```{r}
#annual aggreagate
ggplot(Stor_Mer3) + 
  theme_bw(base_size=12, base_family='Times New Roman') + #change font to Times New Roman, 12pt, Bold
    geom_violin(draw_quantiles = c(.25, .5, .75), aes( x = variable, y = AnnualTotal, fill = variable)) + #plot monthly observed data in greenish blue
   #geom_line(aes(x = node, y = value)) +
    scale_y_continuous(limits = c(0, NA),
                      expand = c(0, NA),
                      labels = comma) +
    scale_x_discrete(limits=c("Livneh (Historical)", "HadGEM2-ES", "CanESM2", "MIROC5", "CNRM-CM5"))+
  scale_fill_manual(values = c("#5A5A5A", "#E69F00", "#F0E442", "#009E73", "#56B4E9")) +

  labs(subtitle = "RCP 8.5 Scenario",
       title = "Merced River",
    x = element_blank(), 
       y = "Total Storage (mcm/year)") + #name of x axis
  theme(legend.position = "none",
        legend.direction = "horizontal",
        legend.box.margin = margin(t = -17),
        plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5),
        strip.placement = "outside",
        strip.background = element_blank(),
        panel.spacing.y = unit(0, "lines"))+
png("Mer_storage_GCMs2.png", units ="in", width=8, height=5, res = 300)
```


```{r}
Livneh_Stor_Tuo <- read_csv("C:/Users/gusta/Box/VICE Lab/RESEARCH/PROJECTS/CERC-WET/Task7_San_Joaquin_Model/Pywr models/results/Binary IFRs x Prices/tuolumne/historical/Livneh/Reservoir_Storage_mcm.csv", col_types = cols(node = col_date(), .default = col_double()))[-c(1:3), c(1,3,7,11, 15)] 
Livneh_Stor_Tuo

Livneh_Stor_Tuo <-Livneh_Stor_Tuo %>%
 mutate(`Livneh (Historical)` = rowSums(Livneh_Stor_Tuo[c(2:5)])) %>%
      filter(between(node, as.Date("1980-10-01"), as.Date("2010-09-30")))
Livneh_Stor_Tuo


CanES_Stor_Tuo <- read_csv("C:/Users/gusta/Box/VICE Lab/RESEARCH/PROJECTS/CERC-WET/Task7_San_Joaquin_Model/Pywr models/results/Binary IFRs x Prices/tuolumne/gcms/CanESM2_rcp85/Reservoir_Storage_mcm.csv", col_types = cols(node = col_date(), .default = col_double()))[-c(1:3), c(1,3,7,11, 15)]
CanES_Stor_Tuo

CanES_Stor_Tuo <- CanES_Stor_Tuo %>%
   mutate(CanESM2 = rowSums(CanES_Stor_Tuo[c(2:5)]))
CanES_Stor_Tuo
  

CNRM_Stor_Tuo <- read_csv("C:/Users/gusta/Box/VICE Lab/RESEARCH/PROJECTS/CERC-WET/Task7_San_Joaquin_Model/Pywr models/results/Binary IFRs x Prices/tuolumne/gcms/CNRM-CM5_rcp85/Reservoir_Storage_mcm.csv", col_types = cols(node = col_date(), .default = col_double()))[-c(1:3), c(1,3,7,11, 15)]
CNRM_Stor_Tuo

CNRM_Stor_Tuo <- CNRM_Stor_Tuo %>%
   mutate(`CNRM-CM5` = rowSums(CNRM_Stor_Tuo[c(2:5)]))

CNRM_Stor_Tuo


HadGEM_Stor_Tuo <- read_csv("C:/Users/gusta/Box/VICE Lab/RESEARCH/PROJECTS/CERC-WET/Task7_San_Joaquin_Model/Pywr models/results/Binary IFRs x Prices/tuolumne/gcms/HadGEM2-ES_rcp85/Reservoir_Storage_mcm.csv", col_types = cols(node = col_date(), .default = col_double()))[-c(1:3), c(1,3,7,11, 15)]
HadGEM_Stor_Tuo

HadGEM_Stor_Tuo <- HadGEM_Stor_Tuo %>%
   mutate(`HadGEM2-ES` = rowSums(HadGEM_Stor_Tuo[c(2:5)]))
HadGEM_Stor_Tuo


MIROC_Stor_Tuo <- read_csv("C:/Users/gusta/Box/VICE Lab/RESEARCH/PROJECTS/CERC-WET/Task7_San_Joaquin_Model/Pywr models/results/Binary IFRs x Prices/tuolumne/gcms/MIROC5_rcp85/Reservoir_Storage_mcm.csv", col_types = cols(node = col_date(), .default = col_double()))[-c(1:3), c(1,3,7,11, 15)]
MIROC_Stor_Tuo
MIROC_Stor_Tuo <- MIROC_Stor_Tuo %>%
   mutate(MIROC5 = rowSums(MIROC_Stor_Tuo[c(2:5)]))

MIROC_Stor_Tuo

```

```{r}
Livneh_Tuo_Stor <- Livneh_Stor_Tuo[-c(2:5)] 
Livneh_Tuo_Stor <- melt(Livneh_Tuo_Stor, id = "node")
Livneh_Tuo_Stor


Stor_Tuo <- cbind(CanES_Stor_Tuo[-c(2:5)], CNRM_Stor_Tuo[-c(2:5)], 
                HadGEM_Stor_Tuo[-c(2:5)], MIROC_Stor_Tuo[-c(2:5)])
Stor_Tuo
 

Stor_Tuo1 <- melt(Stor_Tuo, id = "node")
Stor_Tuo1
```

```{r}
Stor_Tuo2 <- rbind(Stor_Tuo1, Livneh_Tuo_Stor) %>%
  mutate(Month = as.factor(format(as.Date(node, format = "%B"), "%b")),
                           Year = water_year(node, origin = "usgs"),
         Scenario = as.factor("RCP 8.5")) %>%
group_by(Year, Month, variable) %>%
   dplyr::summarize(MonthlyTotal = sum(value))

  

Stor_Tuo2$variable <- factor(Stor_Tuo2$variable, levels = c("Livneh (Historical)", "HadGEM2-ES", "CanESM2", "MIROC5", "CNRM-CM5")) 

Stor_Tuo3 <- Stor_Tuo2 %>%
  group_by(Year, variable) %>%
   dplyr::summarize(AnnualTotal = sum(MonthlyTotal)) 

Stor_Tuo3

```

```{r}
Livneh_Stor_Tuo$GCM <- "Livneh (Historical)" 
CanES_Stor_Tuo$GCM <- "CanESM2"
CNRM_Stor_Tuo$GCM <- "CNRM-CM5"
MIROC_Stor_Tuo$GCM <- "MIROC5"
HadGEM_Stor_Tuo$GCM <- "HadGEM2-ES"


Stor_DonPedro <- rbind(Livneh_Stor_Tuo[-c(2,3,5,6)], CanES_Stor_Tuo[-c(2,3,5,6)],
                       CNRM_Stor_Tuo[-c(2,3,5,6)], HadGEM_Stor_Tuo[-c(2,3,5,6)],
                       MIROC_Stor_Tuo[-c(2,3,5,6)]) %>%
  dplyr::rename(`Don Pedro Reservoir` = `Don Pedro Reservoir_1`)
Stor_DonPedro
 

Stor_DonPedro1 <- melt(Stor_DonPedro, id = c("node", "GCM"))
Stor_DonPedro1

```

```{r}
#Total capacity of Don Pedro is 2504 mcm, 381.0965 mcm is dead pool, so 1/3 of it is 707.6345 



OperCap_DonPedro <- Stor_DonPedro1 %>%
  mutate(Month = as.factor(format(as.Date(node, format = "%B"), "%b")),
                           Year = water_year(node, origin = "usgs"),
         Scenario = as.factor("RCP 8.5"),
         DeadPool = as.numeric(381.0965),
         OperatingCapacity = (value - DeadPool),
         Count = ifelse(OperatingCapacity > 707.6345, 0,1))


OperCap_DonPedro$GCM <- factor(OperCap_DonPedro$GCM, levels = c("Livneh (Historical)","HadGEM2-ES", "CanESM2", "MIROC5", "CNRM-CM5"))
OperCap_DonPedro

```


```{r}
ggplot(Stor_Tuo2) + 
  theme_bw(base_size=12, base_family='Times New Roman') + #change font to Times New Roman, 12pt, Bold
    geom_boxplot(aes( x = Month, y = MonthlyTotal, fill = variable), outlier.alpha = 0.3) + #plot monthly observed data in greenish blue
   #geom_line(aes(x = node, y = value)) +
    scale_y_continuous(limits = c(0, NA),
                      expand = c(0, NA),
                      labels = comma) +
    scale_x_discrete(limits=c("Oct","Nov","Dec", "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep"))+
  scale_fill_manual(values = c("#5A5A5A", "#E69F00", "#F0E442", "#009E73", "#56B4E9")) +

  labs(fill = "RCP 8.5",
       title = "Tuolumne River",
    x = element_blank(), 
       y = "Total Storage (mcm/month)") + #name of x axis
  theme(legend.position = "bottom",
        legend.direction = "horizontal",
        legend.box.margin = margin(t = -17),
        plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5),
        strip.placement = "outside",
        strip.background = element_blank(),
        panel.spacing.y = unit(0, "lines"))+
png("Tuo_storage_GCMs.png", units ="in", width=8, height=5, res = 300)
```

```{r}
#annual aggreagate
ggplot(Stor_Tuo3) + 
  theme_bw(base_size=12, base_family='Times New Roman') + #change font to Times New Roman, 12pt, Bold
    geom_violin(draw_quantiles = c(.25, .5, .75), aes( x = variable, y = AnnualTotal, fill = variable)) + #plot monthly observed data in greenish blue
   #geom_line(aes(x = node, y = value)) +
    scale_y_continuous(limits = c(0, NA),
                      expand = c(0, NA),
                      labels = comma) +
    scale_x_discrete(limits=c("Livneh (Historical)", "HadGEM2-ES", "CanESM2", "MIROC5", "CNRM-CM5"))+
  scale_fill_manual(values = c("#5A5A5A", "#E69F00", "#F0E442", "#009E73", "#56B4E9")) +

  labs(subtitle = "RCP 8.5 Scenario",
       title = "Tuolumne River",
    x = element_blank(), 
       y = "Total Storage (mcm/year)") + #name of x axis
  theme(legend.position = "none",
        #legend.direction = "horizontal",
        #legend.box.margin = margin(t = -19),
        plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5),
        strip.placement = "outside",
        strip.background = element_blank(),
        panel.spacing.y = unit(0, "lines"))+
png("Tuo_storage_GCMs2.png", units ="in", width=8, height=5, res = 300)
```


```{r}
Livneh_Stor_Stn <- read_csv("C:/Users/gusta/Box/VICE Lab/RESEARCH/PROJECTS/CERC-WET/Task7_San_Joaquin_Model/Pywr models/results/Binary IFRs x Prices/stanislaus/historical/Livneh/Reservoir_Storage_mcm.csv", col_types = cols(node = col_date(), .default = col_double()))[-c(1:3), c(1,3,7, 11, 15, 19, 23, 27, 31, 35, 39)] 
Livneh_Stor_Stn

Livneh_Stor_Stn <-Livneh_Stor_Stn %>%
 mutate(`Livneh (Historical)` = rowSums(Livneh_Stor_Stn[c(2:11)])) %>%
      filter(between(node, as.Date("1980-10-01"), as.Date("2010-09-30")))
Livneh_Stor_Stn


CanES_Stor_Stn <- read_csv("C:/Users/gusta/Box/VICE Lab/RESEARCH/PROJECTS/CERC-WET/Task7_San_Joaquin_Model/Pywr models/results/Binary IFRs x Prices/stanislaus/gcms/CanESM2_rcp85/Reservoir_Storage_mcm.csv", col_types = cols(node = col_date(), .default = col_double()))[-c(1:3), c(1,3,7, 11, 15, 19, 23, 27, 31, 35, 39)]
CanES_Stor_Stn

CanES_Stor_Stn <- CanES_Stor_Stn %>%
   mutate(CanESM2 = rowSums(CanES_Stor_Stn[c(2:11)]))
CanES_Stor_Stn
  

CNRM_Stor_Stn <- read_csv("C:/Users/gusta/Box/VICE Lab/RESEARCH/PROJECTS/CERC-WET/Task7_San_Joaquin_Model/Pywr models/results/Binary IFRs x Prices/stanislaus/gcms/CNRM-CM5_rcp85/Reservoir_Storage_mcm.csv", col_types = cols(node = col_date(), .default = col_double()))[-c(1:3), c(1,3,7, 11, 15, 19, 23, 27, 31, 35, 39)]
CNRM_Stor_Stn

CNRM_Stor_Stn <- CNRM_Stor_Stn %>%
   mutate(`CNRM-CM5` = rowSums(CNRM_Stor_Stn[c(2:11)]))

CNRM_Stor_Stn


HadGEM_Stor_Stn <- read_csv("C:/Users/gusta/Box/VICE Lab/RESEARCH/PROJECTS/CERC-WET/Task7_San_Joaquin_Model/Pywr models/results/Binary IFRs x Prices/stanislaus/gcms/HadGEM2-ES_rcp85/Reservoir_Storage_mcm.csv", col_types = cols(node = col_date(), .default = col_double()))[-c(1:3), c(1,3,7, 11, 15, 19, 23, 27, 31, 35, 39)]
HadGEM_Stor_Stn

HadGEM_Stor_Stn <- HadGEM_Stor_Stn %>%
   mutate(`HadGEM2-ES` = rowSums(HadGEM_Stor_Stn[c(2:11)]))
HadGEM_Stor_Stn


MIROC_Stor_Stn <- read_csv("C:/Users/gusta/Box/VICE Lab/RESEARCH/PROJECTS/CERC-WET/Task7_San_Joaquin_Model/Pywr models/results/Binary IFRs x Prices/stanislaus/gcms/MIROC5_rcp85/Reservoir_Storage_mcm.csv", col_types = cols(node = col_date(), .default = col_double()))[-c(1:3), c(1,3,7, 11, 15, 19, 23, 27, 31, 35, 39)]
MIROC_Stor_Stn
MIROC_Stor_Stn <- MIROC_Stor_Stn %>%
   mutate(MIROC5 = rowSums(MIROC_Stor_Stn[c(2:11)]))

MIROC_Stor_Stn

```

```{r}
Livneh_Stn_Stor <- Livneh_Stor_Stn[-c(2:11)] 
Livneh_Stn_Stor <- melt(Livneh_Stn_Stor, id = "node")
Livneh_Stn_Stor

Stor_Stn <- cbind(CanES_Stor_Stn[-c(2:11)], CNRM_Stor_Stn[-c(2:11)], 
                HadGEM_Stor_Stn[-c(2:11)], MIROC_Stor_Stn[-c(2:11)])
Stor_Stn
 

Stor_Stn1 <- melt(Stor_Stn, id = "node")
Stor_Stn1
```

```{r}
Stor_Stn2 <- rbind(Stor_Stn1, Livneh_Stn_Stor) %>%
  mutate(Month = as.factor(format(as.Date(node, format = "%B"), "%b")),
                           Year = water_year(node, origin = "usgs"),
         Scenario = as.factor("RCP 8.5")) %>%
group_by(Year, Month, variable) %>%
   dplyr::summarize(MonthlyTotal = sum(value))
 
  

Stor_Stn2$variable <- factor(Stor_Stn2$variable, levels = c("Livneh (Historical)", "HadGEM2-ES", "CanESM2", "MIROC5", "CNRM-CM5")) 


Stor_Stn3 <- Stor_Stn2 %>%
  group_by(Year, variable) %>%
   dplyr::summarize(AnnualTotal = sum(MonthlyTotal)) 

Stor_Stn3
```

```{r}
Livneh_Stor_Stn$GCM <- "Livneh (Historical)" 
CanES_Stor_Stn$GCM <- "CanESM2"
CNRM_Stor_Stn$GCM <- "CNRM-CM5"
MIROC_Stor_Stn$GCM <- "MIROC5"
HadGEM_Stor_Stn$GCM <- "HadGEM2-ES"

Stor_NewMelones <- rbind(Livneh_Stor_Stn[c(1,7,13)], CanES_Stor_Stn[c(1,7,13)],
                       CNRM_Stor_Stn[c(1,7,13)], HadGEM_Stor_Stn[c(1,7,13)],
                       MIROC_Stor_Stn[c(1,7,13)])%>% #Select only New Melones
    dplyr::rename(`New Melones Lake` = `New Melones Lake_1`)
Stor_NewMelones
 

Stor_NewMelones1 <- melt(Stor_NewMelones, id = c("node", "GCM"))
Stor_NewMelones1

```

```{r}
#Total capacity of New Melones is 2985 mcm, 98.6785 mcm is dead pool, so 1/3 of it is 962.1071667 



OperCap_NewMelones <- Stor_NewMelones1 %>%
  mutate(Month = as.factor(format(as.Date(node, format = "%B"), "%b")),
                           Year = water_year(node, origin = "usgs"),
         Scenario = as.factor("RCP 8.5"),
         DeadPool = as.numeric(98.6785),
         OperatingCapacity = (value - DeadPool),
         Count = ifelse(OperatingCapacity > 962.1072, 0,1))


OperCap_NewMelones$GCM <- factor(OperCap_NewMelones$GCM, levels = c("Livneh (Historical)","HadGEM2-ES", "CanESM2", "MIROC5", "CNRM-CM5"))
OperCap_NewMelones

```


```{r}
ggplot(Stor_Stn2) + 
  theme_bw(base_size=12, base_family='Times New Roman') + #change font to Times New Roman, 12pt, Bold
    geom_boxplot(aes( x = Month, y = MonthlyTotal, fill = variable), outlier.alpha = 0.3) + #plot monthly observed data in greenish blue
   #geom_line(aes(x = node, y = value)) +
    scale_y_continuous(limits = c(0, NA),
                      expand = c(0, NA),
                      labels = comma) +
    scale_x_discrete(limits=c("Oct","Nov","Dec", "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep"))+
  scale_fill_manual(values = c("#5A5A5A", "#E69F00", "#F0E442", "#009E73", "#56B4E9")) +

  labs(fill = "RCP 8.5",
       title = "Stanislaus River",
    x = element_blank(), 
       y = "Total Storage (mcm/month)") + #name of x axis
  theme(legend.position = "bottom",
        legend.direction = "horizontal",
        legend.box.margin = margin(t = -19),
        plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5),
        strip.placement = "outside",
        strip.background = element_blank(),
        panel.spacing.y = unit(0, "lines")) +
png("Stn_storage_GCMs.png", units ="in", width=8, height=5, res = 300)
```

```{r}
#annual aggreagate
ggplot(Stor_Stn3) + 
  theme_bw(base_size=12, base_family='Times New Roman') + #change font to Times New Roman, 12pt, Bold
    geom_violin(draw_quantiles = c(.25, .5, .75), aes( x = variable, y = AnnualTotal, fill = variable)) + #plot monthly observed data in greenish blue
   #geom_line(aes(x = node, y = value)) +
    scale_y_continuous(limits = c(0, NA),
                      expand = c(0, NA),
                      labels = comma) +
    scale_x_discrete(limits=c("Livneh (Historical)", "HadGEM2-ES", "CanESM2", "MIROC5", "CNRM-CM5"))+
  scale_fill_manual(values = c("#5A5A5A", "#E69F00", "#F0E442", "#009E73", "#56B4E9")) +

  labs(subtitle = "RCP 8.5 Scenario",
       title = "Stanislaus River",
    x = element_blank(), 
       y = "Total Storage (mcm/year)") + #name of x axis
  theme(legend.position = "none",
        legend.direction = "horizontal",
        legend.box.margin = margin(t = -17),
        plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5),
        strip.placement = "outside",
        strip.background = element_blank(),
        panel.spacing.y = unit(0, "lines"))+
png("Stn_storage_GCMs2.png", units ="in", width=8, height=5, res = 300)
```


```{r}
Livneh_Stor_USJ <- read_csv("C:/Users/gusta/Box/VICE Lab/RESEARCH/PROJECTS/CERC-WET/Task7_San_Joaquin_Model/Pywr models/results/Binary IFRs x Prices/upper_san_joaquin/historical/Livneh/Reservoir_Storage_mcm.csv", col_types = cols(node = col_date(), .default = col_double()))[-c(1:3), c(1,3,7, 11, 15, 19, 23, 27, 31, 35)] 
Livneh_Stor_USJ

Livneh_Stor_USJ <-Livneh_Stor_USJ %>%
 mutate(`Livneh (Historical)` = rowSums(Livneh_Stor_USJ[c(2:10)])) %>%
      filter(between(node, as.Date("1980-10-01"), as.Date("2010-09-30")))
Livneh_Stor_USJ


CanES_Stor_USJ <- read_csv("C:/Users/gusta/Box/VICE Lab/RESEARCH/PROJECTS/CERC-WET/Task7_San_Joaquin_Model/Pywr models/results/Binary IFRs x Prices/upper_san_joaquin/gcms/CanESM2_rcp85/Reservoir_Storage_mcm.csv", col_types = cols(node = col_date(), .default = col_double()))[-c(1:3), c(1,3,7, 11, 15, 19, 23, 27, 31, 35)]
CanES_Stor_USJ

CanES_Stor_USJ <- CanES_Stor_USJ %>%
   mutate(CanESM2 = rowSums(CanES_Stor_USJ[c(2:10)]))
CanES_Stor_USJ
  

CNRM_Stor_USJ <- read_csv("C:/Users/gusta/Box/VICE Lab/RESEARCH/PROJECTS/CERC-WET/Task7_San_Joaquin_Model/Pywr models/results/Binary IFRs x Prices/upper_san_joaquin/gcms/CNRM-CM5_rcp85/Reservoir_Storage_mcm.csv", col_types = cols(node = col_date(), .default = col_double()))[-c(1:3), c(1,3,7, 11, 15, 19, 23, 27, 31, 35)]
CNRM_Stor_USJ

CNRM_Stor_USJ <- CNRM_Stor_USJ %>%
   mutate(`CNRM-CM5` = rowSums(CNRM_Stor_USJ[c(2:10)]))

CNRM_Stor_USJ


HadGEM_Stor_USJ <- read_csv("C:/Users/gusta/Box/VICE Lab/RESEARCH/PROJECTS/CERC-WET/Task7_San_Joaquin_Model/Pywr models/results/Binary IFRs x Prices/upper_san_joaquin/gcms/HadGEM2-ES_rcp85/Reservoir_Storage_mcm.csv", col_types = cols(node = col_date(), .default = col_double()))[-c(1:3), c(1,3,7, 11, 15, 19, 23, 27, 31, 35)]
HadGEM_Stor_USJ

HadGEM_Stor_USJ <- HadGEM_Stor_USJ %>%
   mutate(`HadGEM2-ES` = rowSums(HadGEM_Stor_USJ[c(2:10)]))
HadGEM_Stor_USJ


MIROC_Stor_USJ <- read_csv("C:/Users/gusta/Box/VICE Lab/RESEARCH/PROJECTS/CERC-WET/Task7_San_Joaquin_Model/Pywr models/results/Binary IFRs x Prices/upper_san_joaquin/gcms/MIROC5_rcp85/Reservoir_Storage_mcm.csv", col_types = cols(node = col_date(), .default = col_double()))[-c(1:3), c(1,3,7, 11, 15, 19, 23, 27, 31, 35)]
MIROC_Stor_USJ
MIROC_Stor_USJ <- MIROC_Stor_USJ %>%
   mutate(MIROC5 = rowSums(MIROC_Stor_USJ[c(2:10)]))

MIROC_Stor_USJ

```

```{r}
Livneh_USJ_Stor <- Livneh_Stor_USJ[-c(2:10)] 
Livneh_USJ_Stor <- melt(Livneh_USJ_Stor, id = "node")
Livneh_USJ_Stor

Stor_USJ <- cbind(CanES_Stor_USJ[-c(2:10)], CNRM_Stor_USJ[-c(2:10)], 
                HadGEM_Stor_USJ[-c(2:10)], MIROC_Stor_USJ[-c(2:10)])
Stor_USJ
 

Stor_USJ2 <- melt(Stor_USJ, id = "node")
Stor_USJ2
```

```{r}
Stor_USJ2 <- rbind(Stor_USJ2, Livneh_USJ_Stor) %>%
  mutate(Month = as.factor(format(as.Date(node, format = "%B"), "%b")),
                           Year = water_year(node, origin = "usgs"),
         Scenario = as.factor("RCP 8.5")) %>%
group_by(Year, Month, variable) %>%
   dplyr::summarize(MonthlyTotal = sum(value))
 
  

Stor_USJ2$variable <- factor(Stor_USJ2$variable, levels = c("Livneh (Historical)", "HadGEM2-ES", "CanESM2", "MIROC5", "CNRM-CM5")) 


Stor_USJ3 <- Stor_USJ2 %>%
  group_by(Year, variable) %>%
   dplyr::summarize(AnnualTotal = sum(MonthlyTotal)) 

Stor_USJ3
```

```{r}
#Storage capacity of Millerton
Livneh_Stor_USJ$GCM <- "Livneh (Historical)" 
CanES_Stor_USJ$GCM <- "CanESM2"
CNRM_Stor_USJ$GCM <- "CNRM-CM5"
MIROC_Stor_USJ$GCM <- "MIROC5"
HadGEM_Stor_USJ$GCM <- "HadGEM2-ES"

Stor_Millerton <- rbind(Livneh_Stor_USJ[c(1,4,12)], CanES_Stor_USJ[c(1,4,12)],
                       CNRM_Stor_USJ[c(1,4,12)], HadGEM_Stor_USJ[c(1,4,12)],
                       MIROC_Stor_USJ[c(1,4,12)]) %>%#Select only New Melones
  dplyr::rename(`Millerton Lake` = `Millerton Lake_1`)
Stor_Millerton
 

Stor_Millerton1 <- melt(Stor_Millerton, id = c("node", "GCM"))
Stor_Millerton1

```

```{r}
#Total capacity of Millerton is 641.42 mcm, 165.3532 mcm is dead pool, so 1/3 of it is 158.6889 



OperCap_Millerton <- Stor_Millerton1 %>%
  mutate(Month = as.factor(format(as.Date(node, format = "%B"), "%b")),
                           Year = water_year(node, origin = "usgs"),
         Scenario = as.factor("RCP 8.5"),
         DeadPool = as.numeric(165.3532),
         OperatingCapacity = (value - DeadPool),
         Count = ifelse(OperatingCapacity > 158.6889, 0,1))


OperCap_Millerton$GCM <- factor(OperCap_Millerton$GCM, levels = c("Livneh (Historical)","HadGEM2-ES", "CanESM2", "MIROC5", "CNRM-CM5"))
OperCap_Millerton

```

```{r}
Basins_Capacity <- rbind(OperCap_McClure, OperCap_DonPedro, OperCap_Millerton, OperCap_NewMelones)

Basins_Capacity$variable <- factor(Basins_Capacity$variable, levels = c("Don Pedro Reservoir","New Melones Lake", "Lake McClure", "Millerton Lake"))

Basins_Capacity
```

```{r}
#Storage Capacity for STN

Storage <- function (Data, Reservoir, Title, Subtitle) {
Data %>%
  filter(variable == Reservoir) %>%
ggplot() +
     theme_bw(base_size=12, base_family='Times New Roman') +
  geom_bar(aes(x= Year, y=Count), stat = "identity") +
ggthemes::scale_color_colorblind() +
   scale_y_continuous(expand = c(0, NA),
                      limits = c(0,366), breaks = c(0, 100, 200, 300, 366)) +
  scale_x_discrete(breaks = c("1981", "1986", "1991", "1996", "2001", "2006", 
                              "2031", "2036", "2041", "2046", "2051", "2056"),
                    expand = c(0, NA))+

  facet_wrap(~GCM, scales = "free_x", ncol = 1, strip.position = "left") +
  
  
  labs(title = Title,
       subtitle = Subtitle,
       
  #  subtitle = "CanESM2",
    x = element_blank(),
       y = "Days") +
 theme(#legend.title = element_blank(),
    #legend.position = "bottom",
     #   legend.direction = "horizontal",
      #  legend.box.margin = margin(t = -17),
        plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5),
        strip.placement = "outside",
        strip.background = element_blank())
#        panel.spacing.y = unit(0, "lines")) +
  
}
```


```{r}
Storage(Basins_Capacity, "New Melones Lake", "Stanislaus River\nNew Melones Lake", "RCP 8.5 Scenario")+
png("Stn_BelowOneThird_Operating_Capacity.png", units ="in", width=3.5, height=8, res = 300)
```

```{r}
Storage(Basins_Capacity, "Millerton Lake", "Upper San Joaquin River\nMillerton Lake", "RCP 8.5 Scenario")+
png("USJ_BelowOneThird_Operating_Capacity.png", units ="in", width=3.5, height=8, res = 300)
```

```{r}
Storage(Basins_Capacity, "Lake McClure", "Merced River\nLake McClure", "RCP 8.5 Scenario")+
png("Mer_BelowOneThird_Operating_Capacity.png", units ="in", width=3.5, height=8, res = 300)
```

```{r}
Storage(Basins_Capacity, "Don Pedro Reservoir", "Tuolumne River\nDon Pedro Reservoir", "RCP 8.5 Scenario")+
png("Tuo_BelowOneThird_Operating_Capacity.png", units ="in", width=3.5, height=8, res = 300)
```

```{r}
ggplot(Basins_Capacity) +
     theme_bw(base_size=12, base_family='Times New Roman') +
  geom_bar(aes(x= Year, y=Count), stat = "identity") +
ggthemes::scale_color_colorblind() +
   scale_y_continuous(expand = c(0, NA),
                      limits = c(0,366), breaks = c(0, 100, 200, 300, 366)) +
  scale_x_discrete(breaks = c("1981", "1986", "1991", "1996", "2001", "2006", 
                              "2031", "2036", "2041", "2046", "2051", "2056"),
                    expand = c(0, NA))+

  facet_wrap(GCM~variable, scales = "free_x", ncol = 4) +
  
  
  labs(title = "Storage Below One Third of Reservoir Operating Capacity",
       subtitle = "RCP 8.5 Scenario",
       
  #  subtitle = "CanESM2",
    x = element_blank(),
       y = "Days") +
 theme(#strip.text.x = element_blank(),
       #legend.title = element_blank(),
    #legend.position = "bottom",
     #   legend.direction = "horizontal",
      #  legend.box.margin = margin(t = -17),
        plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5),
        strip.placement = "outside",
        strip.background = element_blank())+
       # panel.spacing.y = unit(0, "lines")) +
png("AllBasins_BelowOneThird_Operating_Capacity2.png", units ="in", width=8, height=8, res = 300)

```


```{r}
ggplot(Basins_Capacity) +
     theme_bw(base_size=12, base_family='Times New Roman') +
  geom_bar(aes(x= Year, y=Count), stat = "identity") +
ggthemes::scale_color_colorblind() +
   scale_y_continuous(expand = c(0, NA),
                      limits = c(0,366), breaks = c(0, 100, 200, 300, 366)) +
  scale_x_discrete(breaks = c("1981", "1991", "2001", 
                              "2031", "2041", "2051"),
                    expand = c(0, NA))+

  facet_grid(variable~GCM, scales = "free_x") +
  
  
  labs(title = "Storage Below One Third of Reservoir Operating Capacity",
       subtitle = "RCP 8.5 Scenario",
       
  #  subtitle = "CanESM2",
    x = element_blank(),
       y = "Days") +
 theme(#strip.text.x = element_blank(),
       #legend.title = element_blank(),
    #legend.position = "bottom",
     #   legend.direction = "horizontal",
      #  legend.box.margin = margin(t = -17),
        plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5),
        strip.placement = "outside",
        strip.background = element_blank())+
       # panel.spacing.y = unit(0, "lines")) +
png("AllBasins_BelowOneThird_Operating_Capacity_FacetGrid.png", units ="in", width=8.5, height=7, res = 300)
```


```{r}
Basins_Capacity %>%
  filter(GCM == "CanESM2") %>%
ggplot() +
     theme_bw(base_size=12, base_family='Times New Roman') +
  geom_bar(aes(x= Year, y=Count), stat = "identity") +
scale_color_colorblind() +
   scale_y_continuous(expand = c(0, NA),
                      limits = c(0,366), breaks = c(0, 100, 200, 300, 366)) +
  scale_x_discrete(breaks = c("1981", "1986", "1991", "1996", "2001", "2006", 
                              "2031", "2036", "2041", "2046", "2051", "2056"),
                    expand = c(0, NA))+

  facet_wrap(~GCM, scales = "free_x", ncol = 1, strip.position = "left") +
  
  
  labs(title = "New Melones Lake",
       subtitle = "RCP 8.5 Scenario",
       
  #  subtitle = "CanESM2",
    x = element_blank(),
       y = "Days") +
 theme(#legend.title = element_blank(),
    #legend.position = "bottom",
     #   legend.direction = "horizontal",
      #  legend.box.margin = margin(t = -17),
        plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5),
        strip.placement = "outside",
        strip.background = element_blank())
```


```{r}
ggplot(Stor_USJ2) + 
  theme_bw(base_size=12, base_family='Times New Roman') + #change font to Times New Roman, 12pt, Bold
    geom_boxplot(aes( x = Month, y = MonthlyTotal, fill = variable), outlier.alpha = 0.3) + #plot monthly observed data in greenish blue
   #geom_line(aes(x = node, y = value)) +
    scale_y_continuous(limits = c(0, NA),
                      expand = c(0, NA),
                      labels = comma) +
    scale_x_discrete(limits=c("Oct","Nov","Dec", "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep"))+
  scale_fill_manual(values = c("#5A5A5A", "#E69F00", "#F0E442", "#009E73", "#56B4E9")) +

  labs(fill = "RCP 8.5",
       title = "Upper San Joaquin River",
    x = element_blank(), 
       y = "Total Storage (mcm/month)") + #name of x axis
  theme(legend.position = "bottom",
        legend.direction = "horizontal",
        legend.box.margin = margin(t = -17),
        plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5),
        strip.placement = "outside",
        strip.background = element_blank(),
        panel.spacing.y = unit(0, "lines")) +
png("USJ_storage_GCMs.png", units ="in", width=8, height=5, res = 300)
```

```{r}
#annual aggreagate
ggplot(Stor_USJ3) + 
  theme_bw(base_size=12, base_family='Times New Roman') + #change font to Times New Roman, 12pt, Bold
    geom_violin(draw_quantiles = c(.25, .5, .75), aes( x = variable, y = AnnualTotal, fill = variable)) + #plot monthly observed data in greenish blue
   #geom_line(aes(x = node, y = value)) +
    scale_y_continuous(limits = c(0, NA),
                      expand = c(0, NA),
                      labels = comma) +
    scale_x_discrete(limits=c("Livneh (Historical)", "HadGEM2-ES", "CanESM2", "MIROC5", "CNRM-CM5"))+
  scale_fill_manual(values = c("#5A5A5A", "#E69F00", "#F0E442", "#009E73", "#56B4E9")) +

  labs(subtitle = "RCP 8.5 Scenario",
       title = "Upper San Joaquin River",
    x = element_blank(), 
       y = "Total Storage (mcm/year)") + #name of x axis
  theme(legend.position = "none",
        legend.direction = "horizontal",
        legend.box.margin = margin(t = -17),
        plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5),
        strip.placement = "outside",
        strip.background = element_blank(),
        panel.spacing.y = unit(0, "lines"))+
png("USJ_storage_GCMs2.png", units ="in", width=8, height=5, res = 300)
```

```{r}
#Facet wraps of all basins

Stor_Mer2$Basin <- "Merced River"
Stor_Mer3$Basin <- "Merced River"
Stor_Tuo2$Basin <- "Tuolumne River"
Stor_Tuo3$Basin <- "Tuolumne River"
Stor_Stn2$Basin <- "Stanislaus River"
Stor_Stn3$Basin <- "Stanislaus River"
Stor_USJ2$Basin <- "Upper San Joaquin River"
Stor_USJ3$Basin <- "Upper San Joaquin River"



all_storage_monthly <- rbind(Stor_Mer2, Stor_Tuo2, Stor_Stn2 ,Stor_USJ2)

all_storage_monthly$Basin <- factor(all_storage_monthly$Basin, levels = c("Stanislaus River", "Tuolumne River", "Merced River", "Upper San Joaquin River"))
all_storage_monthly

all_storage_year <- rbind(Stor_Mer3, Stor_Tuo3, Stor_Stn3 ,Stor_USJ3)

all_storage_year$Basin <- factor(all_storage_year$Basin, levels = c("Stanislaus River", "Tuolumne River", "Merced River", "Upper San Joaquin River"))
all_storage_year

```

```{r}
all_storage_monthly$Month <- factor(all_storage_monthly$Month, levels = c("Oct", "Nov", "Dec", "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep"))
all_storage_monthly

All_Montlhy_Stats_Stor <- aggregate(MonthlyTotal ~ Month+variable+Basin, all_storage_monthly, summary)
write.csv(All_Montlhy_Stats_Stor, "All_Monthly_Stats_Storage_RCP8.5.csv")

All_Annual_Stats_Stor <- aggregate(AnnualTotal ~ variable+Basin, all_storage_year, summary)
write.csv(All_Annual_Stats_Stor, "All_Annual_Stats_Storage_RCP8.5.csv")
```

```{r}
ggplot(all_storage_monthly) + 
  theme_bw(base_size=12, base_family='Times New Roman') + #change font to Times New Roman, 12pt, Bold
    geom_boxplot(aes( x = Month, y = MonthlyTotal, fill = variable), outlier.alpha = 0.3) + #plot monthly observed data in greenish blue
   #geom_line(aes(x = node, y = value)) +
    scale_y_continuous(limits = c(0, NA),
                      expand = c(0, NA),
                      labels = comma) +
    scale_x_discrete(limits=c("Oct","Nov","Dec", "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep"))+
  scale_fill_manual(values = c("#5A5A5A", "#E69F00", "#F0E442", "#009E73", "#56B4E9")) +

  labs(fill = "RCP 8.5",
       #title = "Upper San Joaquin River",
    x = element_blank(), 
       y = "Total Storage (mcm/month)") + #name of x axis
  theme(legend.position = "bottom",
        legend.direction = "horizontal",
        legend.box.margin = margin(t = -17),
        plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5),
        strip.placement = "outside",
        strip.background = element_blank(),
        panel.spacing.y = unit(0, "lines"))+
  facet_wrap(~Basin, scales = "free_y")+
png("AllBasins_storage_GCMs.png", units ="in", width=8, height=5, res = 300)
```

```{r}
#annual aggreagate
ggplot(all_storage_year) + 
  theme_bw(base_size=12, base_family='Times New Roman') + #change font to Times New Roman, 12pt, Bold
    geom_violin(draw_quantiles = c(.25, .5, .75), aes( x = variable, y = AnnualTotal, fill = variable)) + #plot monthly observed data in greenish blue
   #geom_line(aes(x = node, y = value)) +
    scale_y_continuous(limits = c(0, NA),
                      expand = c(0, NA),
                      labels = comma) +
    scale_x_discrete(limits=c("Livneh (Historical)", "HadGEM2-ES", "CanESM2", "MIROC5", "CNRM-CM5"))+
  scale_fill_manual(values = c("#5A5A5A", "#E69F00", "#F0E442", "#009E73", "#56B4E9")) +

  labs(fill = "RCP 8.5",
       #title = "Upper San Joaquin River",
    x = element_blank(), 
       y = "Total Storage (mcm/year)") + #name of x axis
  theme(legend.position = "bottom",
        legend.direction = "horizontal",
        legend.box.margin = margin(t = -17),
         axis.ticks.x=element_blank(),
        axis.text.x=element_blank(),
        plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5),
        strip.placement = "outside",
        strip.background = element_blank(),
        legend.text = element_text(size = 9),
       legend.key.size = unit(0.75,"line"),
        panel.spacing.y = unit(0, "lines"))+
    facet_wrap(~Basin, scales = "free_y")+
png("AllBasins_Storage_GCMs2.png", units ="in", width=8, height=5, res = 300)
```
