---
title: "Untitled"
author: "Gustavo Facincani Dourado"
date: "7/27/2020"
output: html_document
---

```{r}
library(raster)
library(ncdf4)
library(maptools)
library(foreign)
library(RNetCDF)
library(rgdal)
library(lubridate)

extractPrecip <- function(src, dst, lat, lon, start, end) {

  obsdata <- nc_open(src)
  print(obsdata) # check that dims are lon-lat-time
  
  # get values at location lonlat
  obsoutput <- ncvar_get(obsdata, varid = 'rainfall',
                         start= c(which.min(abs(obsdata$dim$Lon$vals - lon)), # look for closest long
                                  which.min(abs(obsdata$dim$Lat$vals - lat)),  # look for closest lat
                                  1),
                         count = c(1,1,-1)) #count '-1' means 'all values along that dimension'that dimension'
  # create dataframe
  datafinal <- data.frame(dates= obsdatadates, obs = obsoutput)
  
  # get dates
  #obsdatadates <- as.Date(obsdata$dim$Time$vals, origin = '1950-01-01')
  date.start <- start
  date.end <- end
  d <- seq(as.Date(date.start), as.Date(date.end),1)
  datafinal$dates <- d
  datafinal$month <- month(d)
  datafinal$year <- year(d)
  datafinal$day <- day(d)
  datafinal$WY <- datafinal$year + (datafinal$month %in% 10:12) #this method is called vectorization 
  
  write.csv(datafinal, outpath)
  
  return()

}

#climate <- "Livneh"
climate <- "MIROC5"
rcp <- 85
code <- 'DPR_I'
basin <- "TUOR"
lon <- 37.9491  # longitude of location
lat <- -119.7739 # latitude  of location

rootPath = paste("C:/Users/gusta/Desktop/PhD/Classes/ES207")

# source dir
if (climate == "Livneh") {
  start <- '1950-01-01'
  end <- '2099-12-31'
} else {
  start <- '2006-01-01'
  end <- '2099-12-31'
  rcpdir <- paste("rcp", rcp, sep="")
  srcpath <- paste(rootPath)
  filename <- paste(climate, ".rcp", rcp, ".", code, ".1950-2099.monthly.BC.nc", sep="")
}
src <- paste(srcpath, filename, sep="/")

# destination path
dstdir <- paste("C:/Users/gusta/Desktop/PhD/Classes/ES207")
filename <- "rainfall_Hetch_Hetchy_mcm2.csv"
dst <- paste(dstdir, filename, sep="/")

extractPrecip(src, dst, lat, lon, start, end)

```

```{r}
nc <- nc_open("C:/Users/gusta/Desktop/PhD/Classes/ES207/MIROC5.rcp85.DPR_I.1950-2099.monthly.BC.nc")
```

