---
title: "Whiplash Flood Flows"
author: "Gustavo Facincani Dourado"
date: '2023-02-08'
output: html_document
---

```{r}
Mer_Total_Spill <- read.csv("C:/Users/gusta/Box/VICE Lab/RESEARCH/PROJECTS/CERC-WET/Task7_San_Joaquin_Model/pywr_models/results/Energy Prices - 2023-02-07/merced/historical/Livneh/TotalSpill_Flow_mcm.csv")[-c(1,2),] %>%
  dplyr::select(., -contains(".1"))
Mer_Total_Spill
Tuo_Total_Spill <- read.csv("C:/Users/gusta/Box/VICE Lab/RESEARCH/PROJECTS/CERC-WET/Task7_San_Joaquin_Model/pywr_models/results/Energy Prices - 2023-02-07/tuolumne/historical/Livneh/TotalSpill_Flow_mcm.csv")[-c(1,2),] %>%
  dplyr::select(., -contains(".1"))
Tuo_Total_Spill
Stn_Total_Spill <- read.csv("C:/Users/gusta/Box/VICE Lab/RESEARCH/PROJECTS/CERC-WET/Task7_San_Joaquin_Model/pywr_models/results/Energy Prices - 2023-02-07/stanislaus/historical/Livneh/TotalSpill_Flow_mcm.csv")[-c(1,2),] %>%
  dplyr::select(., -contains(".1"))
Stn_Total_Spill
USJ_Total_Spill <- read.csv("C:/Users/gusta/Box/VICE Lab/RESEARCH/PROJECTS/CERC-WET/Task7_San_Joaquin_Model/pywr_models/results/Energy Prices - 2023-02-07/upper_san_joaquin/historical/Livneh/TotalSpill_Flow_mcm.csv")[-c(1,2),] %>%
  dplyr::select(., -contains(".1"))
USJ_Total_Spill
Mer_Unc_Spill <- read.csv("C:/Users/gusta/Box/VICE Lab/RESEARCH/PROJECTS/CERC-WET/Task7_San_Joaquin_Model/pywr_models/results/Energy Prices - 2023-02-07/merced/historical/Livneh/UncontrolledSpill_Flow_mcm.csv")[-c(1,2),] %>%
  dplyr::select(., -contains(".1"))
Mer_Unc_Spill
Tuo_Unc_Spill <- read.csv("C:/Users/gusta/Box/VICE Lab/RESEARCH/PROJECTS/CERC-WET/Task7_San_Joaquin_Model/pywr_models/results/Energy Prices - 2023-02-07/tuolumne/historical/Livneh/UncontrolledSpill_Flow_mcm.csv")[-c(1,2),] %>%
  dplyr::select(., -contains(".1"))
Tuo_Unc_Spill
Stn_Unc_Spill <- read.csv("C:/Users/gusta/Box/VICE Lab/RESEARCH/PROJECTS/CERC-WET/Task7_San_Joaquin_Model/pywr_models/results/Energy Prices - 2023-02-07/stanislaus/historical/Livneh/UncontrolledSpill_Flow_mcm.csv")[-c(1,2),] %>%
  dplyr::select(., -contains(".1"))
Stn_Unc_Spill
USJ_Unc_Spill <- read.csv("C:/Users/gusta/Box/VICE Lab/RESEARCH/PROJECTS/CERC-WET/Task7_San_Joaquin_Model/pywr_models/results/Energy Prices - 2023-02-07/upper_san_joaquin/historical/Livneh/UncontrolledSpill_Flow_mcm.csv")[-c(1,2),] %>%
  dplyr::select(., -contains(".1"))
USJ_Unc_Spill
```

```{r}
Unc_Spill <- cbind(Mer_Unc_Spill, Tuo_Unc_Spill[2], Stn_Unc_Spill[2], USJ_Unc_Spill[2]) %>%
      reshape2::melt(., id = "node") %>%
  mutate(WaterYear = lfstat::water_year(node, origin = "usgs"),
         Occurrence = ifelse(value > 0, 1, 0)) %>%
  group_by(WaterYear, variable) %>%
  summarize(Spill = sum(value),
            Days = sum(Occurrence))
Unc_Spill
```

```{r}
ggplot(Unc_Spill) +
     theme_bw(base_size=12, base_family='Times New Roman') +
  geom_bar(aes(x= WaterYear, y=Days), stat = "identity") +
#ggthemes::scale_color_colorblind() +
   scale_y_continuous(expand = c(0, NA),
                      limits = c(0,NA), breaks = c(0, 10, 20, 30, 40, 50, 60)) +
  scale_x_discrete(breaks = c("1981", "1991", "2001", "2011", 
                              "1951", "1961", "1971"),
                    expand = c(0, NA))+
  facet_wrap(~variable, scales = "free_x", ncol = 4) +
  
  labs(#title = "Storage Below One Third of Reservoir Operating Capacity",
    #  subtitle = "RCP 8.5 Scenario",
       
  #  subtitle = "CanESM2",
    x = element_blank(),
       y = "Uncontrolled Spill Occurrence\n(Days)") +
 theme(#strip.text.x = element_blank(),
       #legend.title = element_blank(),
    #legend.position = "bottom",
     #   legend.direction = "horizontal",
      #  legend.box.margin = margin(t = -17),
        axis.text.x = element_text(angle = -40, vjust=-0.4),
        plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5),
        strip.placement = "outside",
        strip.background = element_blank())+
       # panel.spacing.y = unit(0, "lines")) +
png("AllBasins_UncSpill.png", units ="in", width=10, height=3, res = 300)
```

```{r}
Total_Spill <- cbind(Mer_Total_Spill, Tuo_Total_Spill[2], Stn_Total_Spill[2], USJ_Total_Spill[2]) %>%
      reshape2::melt(., id = "node") %>%
  mutate(WaterYear = lfstat::water_year(node, origin = "usgs"),
         Occurrence = ifelse(value > 0, 1, 0)) %>%
  group_by(WaterYear, variable) %>%
  summarize(Total_Spill = sum(value),
            Days = sum(Occurrence)) 

Total_Spill

Total_Spill2 <- Total_Spill%>%
  group_by(variable) %>%
  summarize(Average_Spill_Days = mean(Days),
         Min_Spill_Days = min(Days),
         Max_Spill_Days = max(Days),
         Average_Spill = mean(Total_Spill),
         Min_Spill = min(Total_Spill),
         Max_Spill = max(Total_Spill))
Total_Spill2

#write_csv(Total_Spill2, "Total_Spill_Whiplash.csv")
```

```{r}
ggplot(Total_Spill) +
     theme_bw(base_size=12, base_family='Times New Roman') +
  geom_bar(aes(x= WaterYear, y=Total_Spill), stat = "identity") +
#ggthemes::scale_color_colorblind() +
   scale_y_continuous(expand = c(0, NA),
                      limits = c(0,NA)) +
  scale_x_discrete(breaks = c("1981", "1991", "2001", "2011", 
                              "1951", "1961", "1971"),
                    expand = c(0, NA))+
  facet_wrap(~variable, scales = "free_x", ncol = 4) +
  
  labs(#title = "Storage Below One Third of Reservoir Operating Capacity",
    #  subtitle = "RCP 8.5 Scenario",
       
  #  subtitle = "CanESM2",
    x = element_blank(),
       y = "Total Flood Control Releases\n(mcm/year)") +
 theme(#strip.text.x = element_blank(),
       #legend.title = element_blank(),
    #legend.position = "bottom",
     #   legend.direction = "horizontal",
      #  legend.box.margin = margin(t = -17),
        axis.text.x = element_text(angle = -40, vjust=-0.4),
        plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5),
        strip.placement = "outside",
        strip.background = element_blank())+
       # panel.spacing.y = unit(0, "lines")) +
png("AllBasins_FloodControl.png", units ="in", width=10, height=3, res = 300)
```

```{r}
Mer_FNF <- read_csv("C:/Users/gusta/Box/VICE Lab/RESEARCH/PROJECTS/CERC-WET/Task7_San_Joaquin_Model/pywr_models/data/Merced River/preprocessed/full_natural_flow_annual_mcm.csv")
Mer_FNF

Tuo_FNF <- read_csv("C:/Users/gusta/Box/VICE Lab/RESEARCH/PROJECTS/CERC-WET/Task7_San_Joaquin_Model/pywr_models/data/Tuolumne River/hydrology/historical/Livneh/preprocessed/full_natural_flow_annual_mcm.csv")
Tuo_FNF

Stn_FNF <- read_csv("C:/Users/gusta/Box/VICE Lab/RESEARCH/PROJECTS/CERC-WET/Task7_San_Joaquin_Model/pywr_models/data/Stanislaus River/hydrology/historical/Livneh/preprocessed/full_natural_flow_annual_mcm.csv")
Stn_FNF

USJ_FNF <- read_csv("C:/Users/gusta/Box/VICE Lab/RESEARCH/PROJECTS/CERC-WET/Task7_San_Joaquin_Model/pywr_models/data/Upper San Joaquin River/hydrology/historical/Livneh/preprocessed/full_natural_flow_annual_mcm.csv")
USJ_FNF
```


```{r}
FNF <- cbind(USJ_FNF, Tuo_FNF[2], Stn_FNF[2], Mer_FNF[2])

colnames(FNF) <- c("Date", "Merced", "Tuolumne", "Stanislaus", "Upper San Joaquin") 

FNF <- FNF %>%
  mutate(flow = rowSums(.[2:5])) 
FNF
```
```{r}
#Get quintiles

quintiles_1951 <- quantile(FNF$flow, probs = seq(0, 1, 1/5)) 
quintiles_1951
quintiles_1951[1]
```

```{r}

FNF_Total <- FNF[-c(1,65),] %>%
  mutate(Quintile = ifelse(flow < quantile(FNF$flow, probs = seq(0,1,1/5))[2], "1st Quintile", 
                    ifelse(flow >= quantile(FNF$flow, probs = seq(0,1,1/5))[2] & flow < quantile(FNF$flow, probs = seq(0,1,1/5))[3], "2nd Quintile",
                    ifelse(flow >= quantile(FNF$flow, probs = seq(0,1,1/5))[3] & flow < quantile(FNF$flow, probs = seq(0,1,1/5))[4], "3rd Quintile",
                    ifelse(flow >= quantile(FNF$flow, probs = seq(0,1,1/5))[4] & flow < quantile(FNF$flow, probs = seq(0,1,1/5))[5], "4th Quintile", "5th Quintile")))))

FNF_Total
```
```{r}
FNF2 <- FNF

colnames(FNF2) <- c("Date", "Exchequer.Dam.Flood.Release", "Don.Pedro.Lake.Flood.Control", "New.Melones.Lake.Flood.Control", "Millerton.Lake.Flood.Release") 

FNF3 <- FNF_Total[,c(1,7)] %>% rename(WaterYear = Date) %>% mutate(WaterYear = as.factor(WaterYear))


FNF2 <- FNF2%>%
      reshape2::melt(., id = "Date") %>%
  rename(WaterYear = Date) %>%
  mutate(WaterYear = as.factor(WaterYear)) %>%
  inner_join(Total_Spill, by = c("WaterYear", "variable")) %>%
  inner_join(FNF3, by = "WaterYear") %>%
  mutate(Percentage_of_FNF = (Total_Spill/value)*100)
FNF2
```

```{r}
#Loading packages to be used
library(tidyverse)
library(readr)
library(extrafont)
library(ggplot2)
library(ggthemes)
library(stringr)
library(dplyr)
library(grid)
library(gridExtra)
library(lubridate)
library(cder)

#Getting observed data from CDEC for each basin using CDEC's package
#Stanislaus
SNS.obs <- cdec_query("SNS", "65", "M",  "1905-01-01", "2022-12-31")
SNS.obs$DateTime <- as.Date(SNS.obs$DateTime, format = "%Y/%m/%d")
#Merced
Mer.obs <- cdec_query("MRC", 65, "M",  "1905-01-01", "2022-12-31")
Mer.obs
Mer.obs$DateTime <- as.Date(Mer.obs$DateTime, format = "%Y/%m/%d")
#Tuolumne
TLG.obs <- cdec_query("TLG", 65, "M",  "1905-01-01", "2022-12-31")
TLG.obs$DateTime <- as.Date(TLG.obs$DateTime, format = "%Y/%m/%d")
#Upper San Joaquin
SJF.obs <- cdec_query("SJF", 65, "M",  "1905-01-01", "2022-12-31")
SJF.obs$DateTime <- as.Date(SJF.obs$DateTime, format = "%Y/%m/%d")

#Converting the flows in Acre-feet to million cubic meters
SJF.obs$Value <- SJF.obs$Value/810.71318210885
SNS.obs$Value <- SNS.obs$Value/810.71318210885
Mer.obs$Value <- Mer.obs$Value/810.71318210885
TLG.obs$Value <- TLG.obs$Value/810.71318210885 #%>%
#  group_by(month, year)
```

```{r}
#Cleaning the data

full <- rbind(SNS.obs, SJF.obs, Mer.obs, TLG.obs)

#Selecting only the data that is interesting into
full <- full %>% 
  rename(Obs_flow = Value, Date = DateTime) %>% #renaming columns to identify them easily
  mutate(Date = as.Date(Date, format = "%Y/%m/%d"),
         WaterYear = as.numeric(lfstat::water_year(Date, origin = "usgs"))+1904) %>%
  group_by(WaterYear) %>%
  summarize(Obs_flow = sum(Obs_flow))
full
```

```{r}

full2 <- full %>% filter(!WaterYear < 1906 & !WaterYear > 2022) %>%
  mutate(Quintile = ifelse(Obs_flow < quantile(full$Obs_flow, probs = seq(0,1,1/5))[2], "1st Quintile", 
                    ifelse(Obs_flow >= quantile(full$Obs_flow, probs = seq(0,1,1/5))[2] & Obs_flow < quantile(full$Obs_flow, probs = seq(0,1,1/5))[3], "2nd Quintile",
                    ifelse(Obs_flow >= quantile(full$Obs_flow, probs = seq(0,1,1/5))[3] & Obs_flow < quantile(full$Obs_flow, probs = seq(0,1,1/5))[4], "3rd Quintile",
                    ifelse(Obs_flow >= quantile(full$Obs_flow, probs = seq(0,1,1/5))[4] & Obs_flow < quantile(full$Obs_flow, probs = seq(0,1,1/5))[5], "4th Quintile", "5th Quintile")))))

full2

Quintiles_1906 <- round(quantile(full$Obs_flow, probs = seq(0,1,1/5)), 1)
Quintiles_1906
```
```{r}
linveh <- as.data.frame(quintiles_1951) %>% mutate(Period = "1951-2013") %>% rename(Quintile = quintiles_1951)
linveh

cdec = as.data.frame(Quintiles_1906) %>% mutate(Period = "1906-2022") %>% rename(Quintile = Quintiles_1906)
cdec

complete <- rbind(cdec, linveh)
complete


livneh2 <- formattable::comma(round(quintiles_1951,1),1)  
livneh2
```


```{r}
ggplot(full2)+

    theme_bw(base_size=12, base_family='Times New Roman') + #change font to Times New     
  
          geom_bar(aes(x = WaterYear, y = Obs_flow, fill = Quintile), stat = "identity") + 

  scale_y_continuous(limits = c(NA, NA),
                      expand = c(0, NA),
                      labels=scales::comma) +
   
   scale_x_continuous(breaks = c(1906, 1921, 1936, 1951, 1966, 1981, 1996, 2011, 2022),
      expand = c(0, 0))+
  
  scale_fill_manual(values = c("tomato2", "orange", "gray", "gray", "dodgerblue2"))+

  geom_text(aes( 2027.2, quantiles[2]-400, label = "1st Quintile", vjust = -1), size = 3, color = "tomato2")+
  geom_text(aes( 2027.2, quantiles[3]-400, label = "2nd Quintile", vjust = -1), size = 3, color = "orange")+
  geom_text(aes( 2027.2, quantiles[5]-400, label = "3rd Quintile", vjust = -1), size = 3, color = "dodgerblue2")+

  geom_hline(yintercept = complete[c(2,3,5),]$Quintile, linetype = c("dashed", "dashed", "dashed"), color = "black")+
  
  labs(fill = "",
    x = element_blank(), 
       y = "Full Natural Flow (mcm/year)") + #name of x axis
  theme(plot.margin = unit(c(1,3.5,1,1), "lines"),
        legend.position = "bottom",
        legend.direction = "horizontal",
        legend.box.margin = margin(t = -10),
        plot.title = element_text(hjust = 0.5),
           plot.subtitle = element_text(hjust = 0.5),
        strip.placement = "outside",
        strip.background = element_blank(),
        panel.spacing.y = unit(0, "lines"),
        legend.box = "horizontal")+
  
   coord_cartesian(xlim = c(1905.4, 2022.6), # This focuses the x-axis on the range of interest
                      clip = 'off') +   # This keeps the labels from disappearing
  
  png("Allbasins_FNF_per_mcm_CDEC.png", units ="in", width=10, height=5, res = 300)
  #facet_wrap(, ncol = 1, scales ="free_x", strip.position= "left")
```


```{r}
ggplot(FNF2) +
     theme_bw(base_size=12, base_family='Times New Roman') +
    geom_rect(aes(fill = Quintile, xmin = as.numeric(WaterYear)-0.5, xmax = as.numeric(WaterYear)+0.5, ymin = -Inf, ymax = Inf), alpha = 0.5)+
  geom_bar(aes(x= as.numeric(WaterYear), y=Days), stat = "identity") +
   geom_line(aes(x= as.numeric(WaterYear), y=Percentage_of_FNF*3.41)) +
#ggthemes::scale_color_colorblind() +
   scale_y_continuous(expand = c(0, NA),
                      limits = c(0,NA), 
                   sec.axis = sec_axis( trans=~./3.41, name= "Percentage of FNF (%)"))+#, breaks = c(0, 10, 20, 30, 40, 50, 60)) +
  scale_x_discrete(breaks = c("1981", "1991", "2001", "2011", 
                              "1951", "1961", "1971"),
                    expand = c(0, NA))+
    scale_fill_manual(values = c("tomato2", "orange", "white", "white", "dodgerblue2"))+

  facet_wrap(~variable, scales = "free_x", ncol = 1) +
  
  labs(#title = "Storage Below One Third of Reservoir Operating Capacity",
    #  subtitle = "RCP 8.5 Scenario",
       
  #  subtitle = "CanESM2",
    x = element_blank(),
       y = "Uncontrolled Spill Occurrence\n(Days)") +
 theme(#strip.text.x = element_blank(),
       #legend.title = element_blank(),
    legend.position = "bottom",
     #   legend.direction = "horizontal",
      #  legend.box.margin = margin(t = -17),
        axis.text.x = element_text(angle = -40, vjust=-0.4),
        plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5),
        strip.placement = "outside",
        strip.background = element_blank())+
       # panel.spacing.y = unit(0, "lines")) +
png("AllBasins_Percentageofflow.png", units ="in", width= 6, height=10, res = 300)

```




```{r}
ggplot(FNF_Total)+#  == "ACCESS1-0" | variable == "GFDL-CM3")) + 
  theme_bw(base_size=12, base_family='Times New Roman') + #change font to Times New Roman, 12pt, Bold
  geom_rect(aes(fill = Quintile, xmin = as.numeric(Date)-0.5, xmax = as.numeric(Date)+0.5, ymin = -Inf, ymax = Inf), alpha = 0.5)+
    scale_y_continuous(limits = c(NA, NA),
                      expand = c(0, NA),
                      labels=scales::comma) +
   
      geom_line(aes( x = as.numeric(Date), y = flow)) + #plot monthly observed data in greenish blue
   scale_x_continuous(#breaks = c("1951", "1981", "1991", "2001", "2011"),
      expand = c(0, NA))+

  
  ggplot(full2)+

    theme_bw(base_size=12, base_family='Times New Roman') + #change font to Times New     
  
          geom_bar(aes(x = WaterYear, y = Obs_flow, fill = Quintile), stat = "identity") + 

  scale_y_continuous(limits = c(NA, NA),
                      expand = c(0, NA),
                      labels=scales::comma) +
   
   scale_x_continuous(breaks = c(1906, 1921, 1936, 1951, 1966, 1981, 1996, 2011, 2022),
      expand = c(0, 0))+
  
  scale_fill_manual(values = c("tomato2", "orange", "gray", "gray", "dodgerblue2"))+

  geom_hline(yintercept = complete[c(2,3,5, 8, 9, 11),]$Quintile, linetype = c("solid", "solid", "solid", "dashed", "dashed", "dashed"), color = "black")+
  
  geom_text(aes( 2027.3, quantiles[2]-400, label = quantiles[2], vjust = -1), size = 3, color = "tomato2")+
  geom_text(aes( 2027.3, quantiles[3]-400, label = quantiles[3], vjust = -1), size = 3, color = "orange")+
  geom_text(aes( 2027.3, quantiles[5]-400, label = quantiles[4], vjust = -1), size = 3, color = "dodgerblue2")+

  
  scale_fill_manual(values = c("tomato2", "orange", "white", "white", "dodgerblue2"))+
  
# scale_linetype_manual(values = c("dotted", "longdash", "dotdash", "solid"), name = "Energy Percentiles")+ #"Basin")+ #c("Stanislaus River", "Tuolumne River", "Merced River", "Upper San Joaquin River"), name = "Basin")+
  
  labs(fill = "Water Year Type",
      # title = "Baseline (2009 prices)",
       #subtitle = "Merced River",
    x = element_blank(), 
       y = "Full Natural Flow (mcm/month)") + #name of x axis
  theme(legend.position = "bottom",
        legend.direction = "horizontal",
        legend.box.margin = margin(t = -10),
        plot.title = element_text(hjust = 0.5),
           plot.subtitle = element_text(hjust = 0.5),
        strip.placement = "outside",
        strip.background = element_blank(),
        panel.spacing.y = unit(0, "lines"),
        legend.box = "horizontal")+
  
   coord_cartesian(xlim = c(1905.4, 2013.6), # This focuses the x-axis on the range of interest
                      clip = 'off') +
  png("Allbasins_FNF_per_mcm.png", units ="in", width=8, height=5, res = 300)
  #facet_wrap(, ncol = 1, scales ="free_x", strip.position= "left")
```

```{r}
ggplot(FNF_Total)+#  == "ACCESS1-0" | variable == "GFDL-CM3")) + 
  theme_bw(base_size=12, base_family='Times New Roman') + #change font to Times New     
  scale_y_continuous(limits = c(NA, NA),
                      expand = c(0, NA),
                      labels=scales::comma) +
   
      geom_bar(aes(x = as.numeric(Date), y = flow, fill = Quintile), stat = "identity") + #plot monthly observed data in greenish blue
   scale_x_continuous(breaks = c(1951, 1961, 1971, 1981, 1991, 2001, 2011),
      expand = c(0, NA))+
  scale_fill_manual(values = c("tomato2", "orange", "gray", "gray", "dodgerblue2"))+

geom_hline(yintercept = complete[c(2,3,5, 8, 9, 11),]$Quintile, linetype = c("solid", "solid", "solid", "dashed", "dashed", "dashed"), color = "black")+
  
  geom_text(aes( 2016, livneh2[2]-400, label = livneh2[2], vjust = -1), size = 3, color = "tomato2")+
  geom_text(aes( 2016, livneh2[3]-400, label = livneh2[3], vjust = -1), size = 3, color = "orange")+
  geom_text(aes( 2016, livneh2[5]-400, label = livneh2[5], vjust = -1), size = 3, color = "dodgerblue2")+
  
  
  labs(fill = "",
    x = element_blank(), 
       y = "Full Natural Flow (mcm/year)") + #name of x axis
  theme(plot.margin = unit(c(1,3.5,1,1), "lines"),
        legend.position = "bottom",
        legend.direction = "horizontal",
        legend.box.margin = margin(t = -10),
        plot.title = element_text(hjust = 0.5),
           plot.subtitle = element_text(hjust = 0.5),
        strip.placement = "outside",
        strip.background = element_blank(),
        panel.spacing.y = unit(0, "lines"),
        legend.box = "horizontal")+
  
   coord_cartesian(xlim = c(1950.5, 2013.6), # This focuses the x-axis on the range of interest
                      clip = 'off') +
  png("Allbasins_FNF_per_mcm_Livneh.png", units ="in", width=8, height=5, res = 300)
  #facet_wrap(, ncol = 1, scales ="free_x", strip.position= "left")
```

```{r}

  ggplot(full2, aes(x= factor(0), y = Obs_flow, fill= Quintile)) + geom_violin(draw_quantiles = c(.2, .4, .6, .8)) +   theme_bw(base_size=12, base_family='Times New Roman') + #change font to Times New     

scale_y_continuous(limits = c(0, NA),
                      expand = c(0, NA),
                      labels=scales::comma)+
geom_hline(yintercept = complete[c(2,3,5),]$Quintile, linetype = c("dashed", "dashed", "dashed"), color = "black")+
  
    scale_fill_manual(values = c("tomato2", "orange", "gray", "gray", "dodgerblue2"))+
  
  labs(fill = "",
    x = element_blank(), 
       y = "Full Natural Flow (mcm/year)") + #name of x axis
  theme(plot.margin = unit(c(1,3.5,1,1), "lines"),
        legend.position = "bottom",
        legend.direction = "horizontal",
        legend.box.margin = margin(t = -10),
        plot.title = element_text(hjust = 0.5),
           plot.subtitle = element_text(hjust = 0.5),
        strip.placement = "outside",
        strip.background = element_blank(),
        panel.spacing.y = unit(0, "lines"),
        legend.box = "horizontal",
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())+
  png("Allbasins_FNF_per_mcm_Livneh_boxplot.png", units ="in", width=8, height=5, res = 300)
  #facet_wrap(, ncol = 1, scales ="free_x", strip.position= "left")
```

```{r}
All_FloodRelease <- list.files("C:/Users/gusta/Box/VICE Lab/RESEARCH/PROJECTS/CERC-WET/Task7_San_Joaquin_Model/pywr_models/results/Whiplash - 2023-03-13/", recursive=TRUE) %>%
 # grep("D2W1D2", ., value = TRUE) %>%
  #grep("merced", ., value = TRUE) %>%
  grep(#"Hydropower_Energy"
    "TotalSpill_Flow_mcm.csv", ., value = TRUE)

head(All_FloodRelease)
```

```{r}
filelist_FloodRelease <- lapply(paste("C:/Users/gusta/Box/VICE Lab/RESEARCH/PROJECTS/CERC-WET/Task7_San_Joaquin_Model/pywr_models/results/Whiplash - 2023-03-13/",All_FloodRelease,sep=""), read.csv)

#if necessary, assign names to data.frames
names(filelist_FloodRelease) <- paste(All_FloodRelease)
```


```{r}
filelist_FloodRelease2<- invisible(lapply(names(filelist_FloodRelease), function(x) assign(x,filelist_FloodRelease[[x]][-c(1,2),]%>% 
                                                                   mutate(Sequence = substr(str_split(names(filelist_FloodRelease[x]), "/")[[1]][3], 1,5), 
                                                                          Scenario =paste(substr(str_split(names(filelist_FloodRelease[x]), "/")[[1]][3], 11,14), substr(str_split(names(filelist_FloodRelease[x]), "/")[[1]][3], 11,12), sep=""),
                                                                           Scenario2 =substr(str_split(names(filelist_FloodRelease[x]), "/")[[1]][3], 11,12),
                                                                          Scenario3 =substr(str_split(names(filelist_FloodRelease[x]), "/")[[1]][3], 13,14),
                                                                          Number = substr(str_split(names(filelist_FloodRelease[x]), "/")[[1]][3], 16,20),
                                                                          Basin = str_split(names(filelist_FloodRelease[x]),"/")[[1]][1]),envir=.GlobalEnv))) 
head(filelist_FloodRelease2)

```

```{r}
FloodRelease_Mer <- filelist_FloodRelease2 %>%
  lapply(., function(x) filter(x, Basin == "merced"))%>%
  do.call("rbind", .) %>%
  dplyr::select(., -contains(".1")) %>%
 # mutate(Total = rowSums(.[c(2:3)]))%>%
#  dplyr::select(node, Sequence, Scenario, Number,  Basin) %>%
  reshape2::melt(., by = c("node", "Sequence", "Scenario", "Scenario2", "Scenario3", "Number", "Basin")) %>%
  mutate(node = as.Date(node, "%Y-%m-%d"))
FloodRelease_Mer

FloodRelease_Tuo <- filelist_FloodRelease2 %>%
  lapply(., function(x) filter(x, Basin == "tuolumne"))%>%
  do.call("rbind", .) %>%
  dplyr::select(., -contains(".1")) %>%
  #mutate(Total = rowSums(.[c(2:5)]))%>%
#  dplyr::select(node, Sequence, Scenario, Number,  Basin) %>%
  reshape2::melt(., by = c("node", "Sequence", "Scenario", "Scenario2", "Scenario3", "Number", "Basin")) %>%
  mutate(node = as.Date(node, "%Y-%m-%d"))
FloodRelease_Tuo

FloodRelease_Stn <- filelist_FloodRelease2 %>%
  lapply(., function(x) filter(x, Basin == "stanislaus"))%>%
  do.call("rbind", .) %>%
  dplyr::select(., -contains(".1")) %>%
 # mutate(Total = rowSums(.[c(2:11)]))%>%
 # dplyr::select(node, Sequence, Scenario, Number,  Basin) %>%
  reshape2::melt(., by = c("node", "Sequence", "Scenario", "Scenario2", "Scenario3", "Number", "Basin")) %>%
  mutate(node = as.Date(node, "%Y-%m-%d"))
FloodRelease_Stn

FloodRelease_USJ <- filelist_FloodRelease2 %>%
  lapply(., function(x) filter(x, Basin == "upper_san_joaquin"))%>%
  do.call("rbind", .) %>%
  dplyr::select(., -contains(".1")) %>%
 # mutate(Total = rowSums(.[c(2:10)]))%>%
 # dplyr::select(node, Sequence, Scenario, Number,  Basin) %>%
  reshape2::melt(., by = c("node", "Sequence", "Scenario", "Scenario2", "Scenario3", "Number", "Basin")) %>%
  mutate(node = as.Date(node, "%Y-%m-%d"))
FloodRelease_USJ

All_FloodRelease <- rbind(FloodRelease_Mer, FloodRelease_Tuo, FloodRelease_Stn, FloodRelease_USJ) %>%
  mutate(WaterYear = lfstat::water_year(node, origin = "usgs")) %>%
  group_by(WaterYear, Sequence, Scenario, Scenario2, Scenario3, Number, Basin, variable) %>%
  summarize(value = sum(value))
All_FloodRelease


All_FloodRelease$variable <- factor(All_FloodRelease$variable, levels = c("New.Melones.Lake.Flood.Control",  "Don.Pedro.Lake.Flood.Control","Exchequer.Dam.Flood.Release", "Millerton.Lake.Flood.Release"))
```
```{r}
All_FloodRelease_new <- All_FloodRelease %>% mutate(Basin = replace(Basin, Basin == 'merced', 'MER')) %>%
mutate(Basin = replace(Basin, Basin == 'stanislaus', 'STN')) %>%
mutate(Basin = replace(Basin, Basin == 'tuolumne', 'TUO')) %>%
mutate(Basin = replace(Basin, Basin == 'upper_san_joaquin', 'USJ'))
All_FloodRelease_new

All_FloodRelease_new$Basin <- factor(All_FloodRelease_new$Basin, levels = c("STN", "TUO", "MER", "USJ"))
```



```{r}
All_FloodRelease_new$YearType <- ifelse(All_FloodRelease_new$Scenario == "D2W1D2" & All_FloodRelease_new$WaterYear == "2003", "Wet", 
ifelse(All_FloodRelease_new$WaterYear == "2003" & All_FloodRelease_new$Scenario == "D2W2D2", "Wet", 
       ifelse(All_FloodRelease_new$WaterYear == "2004" & All_FloodRelease_new$Scenario == "D2W2D2", "Wet",
       ifelse(All_FloodRelease_new$Scenario == "D3W1D3" & All_FloodRelease_new$WaterYear == "2004", "Wet",
ifelse(All_FloodRelease_new$WaterYear == "2004" & All_FloodRelease_new$Scenario == "D3W2D3", "Wet", 
       ifelse(All_FloodRelease_new$WaterYear == "2005" & All_FloodRelease_new$Scenario == "D3W2D3", "Wet", 
       ifelse(All_FloodRelease_new$Scenario == "D4W1D4" & All_FloodRelease_new$WaterYear == "2005", "Wet", 
ifelse(All_FloodRelease_new$WaterYear == "2005" & All_FloodRelease_new$Scenario == "D4W2D4", "Wet", 
       ifelse(All_FloodRelease_new$WaterYear == "2006" & All_FloodRelease_new$Scenario == "D4W2D4", "Wet", 
       ifelse(All_FloodRelease_new$Scenario == "D5W1D5" & All_FloodRelease_new$WaterYear == "2006", "Wet",
ifelse(All_FloodRelease_new$WaterYear == "2006" & All_FloodRelease_new$Scenario == "D5W2D5", "Wet",
       ifelse(All_FloodRelease_new$WaterYear == "2007" & All_FloodRelease_new$Scenario == "D5W2D5", "Wet","Dry"))))))))))))

```


```{r}
ggplot(All_FloodRelease2) +
     theme_bw(base_size=12, base_family='Times New Roman') +
  geom_line(aes(x= as.numeric(WaterYear), y=value, color = Number)) +
   #geom_ribbon(ymin=-Inf, aes(x= as.Date(WaterYear, "%Y"), y= Spill, ymax=Spill, fill = Number), alpha=0.4) +
  geom_rect(aes(color = NULL, fill = YearType, xmin = (as.numeric(WaterYear))-0.5, xmax = (as.numeric(WaterYear))+0.5, ymin = -Inf, ymax = Inf), alpha =0.025)+
    scale_fill_manual(values = c("white", "lightblue"))+
    stat_summary(mapping = aes(x=as.numeric(WaterYear), y = value), geom="ribbon", fun.data=mean_cl_normal, fun.args=list(conf.int=0.95), fill="darkgray", alpha = 0.65)+

  stat_summary(mapping = aes(x=as.numeric(WaterYear), y = value), geom="line", fun.y=mean, linetype = "dashed")+

scale_y_continuous(expand = c(0, 0)) +
scale_x_continuous(expand = c(0, 0), limits = c(1,NA), breaks = c(1,3,5,7,9,11))+
  facet_grid(Basin~Scenario3+Scenario2, scales = "free", space = "free_x") +
  
  
  labs(
    x = element_blank(),
       y = "Total Flood Control Releases (mcm/year)") +
 theme(
    legend.position = "none",
        axis.text.x = element_text(angle = -40, vjust=-0.4),
        plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5),
        strip.placement = "outside",
        strip.background = element_blank())+
       # panel.spacing.y = unit(0, "lines")) +
png("AllBasins_FloodControl_Whiplash_withSpill_May2.png", units ="in", width=12, height=7, res = 300)
```

```{r}
ggplot(All_FloodRelease_new%>% filter(Scenario == "D5W1D5" | Scenario == "D5W2D5")) +
     theme_bw(base_size=12, base_family='Times New Roman') +
  geom_line(aes(x= as.numeric(WaterYear), y=value, color = Number)) +
   #geom_ribbon(ymin=-Inf, aes(x= as.Date(WaterYear, "%Y"), y= Spill, ymax=Spill, fill = Number), alpha=0.4) +
  geom_rect(aes(color = NULL, fill = YearType, xmin = (as.numeric(WaterYear))-0.5, xmax = (as.numeric(WaterYear))+0.5, ymin = -Inf, ymax = Inf), alpha =0.025)+
    scale_fill_manual(values = c("white", "lightblue"))+
    stat_summary(mapping = aes(x=as.numeric(WaterYear), y = value), geom="ribbon", fun.data=mean_cl_normal, fun.args=list(conf.int=0.95), fill="darkgray", alpha = 0.65)+

  stat_summary(mapping = aes(x=as.numeric(WaterYear), y = value), geom="line", fun.y=mean, linetype = "dashed")+

  scale_color_manual(values = wesanderson::wes_palette("Zissou1", 25, type = "continuous"))+
  
scale_y_continuous(labels = scales::comma,expand = c(0, 0)) +
scale_x_continuous( expand = c(0, 0), limits = c(1,NA), breaks = c(1,3,5,7,9,11))+
  facet_grid(Basin~Scenario3+Scenario2, scales = "free", space = "free_x") +
  
  
  labs(
    x = element_blank(),
       y = "Total Flood Control Releases (mcm/year)") +
 theme(
    legend.position = "none",
        axis.text.x = element_text(angle = -40, vjust=-0.4),
        plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5),
        strip.placement = "outside",
        strip.background = element_blank())+
       # panel.spacing.y = unit(0, "lines")) +
png("AllBasins_FloodControl_Whiplash_withSpill_Jluy22.png", units ="in", width=7, height=5, res = 300)
```

```{r}
ggplot(All_FloodRelease) +
     theme_bw(base_size=12, base_family='Times New Roman') +
  geom_line(aes(x= as.Date(WaterYear, "%Y"), y=value, color = Number)) +
  # geom_ribbon(ymin=-Inf, aes(x= as.Date(WaterYear, "%Y"), y= Spill, ymax=Spill, color = Number), fill='gray', alpha=0.4) +
#ggthemes::scale_color_colorblind() +
   scale_y_continuous(expand = c(0, NA),
                      limits = c(0,NA)) +
  #scale_x_discrete(breaks = c("1981", "1991", "2001", "2011", 
         #                     "1951", "1961", "1971"),
          #          expand = c(0, NA))+
  facet_grid(variable~Scenario, scales = "free_x") +
  
  labs(#title = "Storage Below One Third of Reservoir Operating Capacity",
    #  subtitle = "RCP 8.5 Scenario",
       
  #  subtitle = "CanESM2",
    x = element_blank(),
       y = "Total Flood Control Releases\n(mcm/year)") +
 theme(#strip.text.x = element_blank(),
       #legend.title = element_blank(),
    legend.position = "none",
     #   legend.direction = "horizontal",
      #  legend.box.margin = margin(t = -17),
        axis.text.x = element_text(angle = -40, vjust=-0.4),
        plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5),
        strip.placement = "outside",
        strip.background = element_blank())+
       # panel.spacing.y = unit(0, "lines")) +
png("AllBasins_FloodControl_Whiplash_March2023_2.png", units ="in", width=20, height=10, res = 300)
```


```{r}
ggplot(All_FloodRelease_new%>% filter(Scenario == "D5W1D5" | Scenario == "D5W2D5")) +
     theme_bw(base_size=12, base_family='Times New Roman') +
  geom_line(aes(x= as.Date(WaterYear, "%Y"), y=value, color = Number)) +
  # geom_ribbon(ymin=-Inf, aes(x= as.Date(WaterYear, "%Y"), y= Spill, ymax=Spill, color = Number), fill='gray', alpha=0.4) +
#ggthemes::scale_color_colorblind() +
   scale_y_continuous(labels = scales::comma, expand = c(0, NA),
                      limits = c(0,NA)) +
  #scale_x_discrete(breaks = c("1981", "1991", "2001", "2011", 
         #                     "1951", "1961", "1971"),
          #          expand = c(0, NA))+
  facet_grid(Basin~Scenario3+Scenario2, scales = "free") +
  scale_color_manual(values = wes_palette("Zissou1", 25, type = "continuous"))+
  labs(#title = "Storage Below One Third of Reservoir Operating Capacity",
    #  subtitle = "RCP 8.5 Scenario",
       
  #  subtitle = "CanESM2",
    x = element_blank(),
       y = "Total Flood Control Releases (mcm/year)") +
 theme(#strip.text.x = element_blank(),
       #legend.title = element_blank(),
    legend.position = "none",
     #   legend.direction = "horizontal",
      #  legend.box.margin = margin(t = -17),
        axis.text.x = element_text(angle = -40, vjust=-0.4),
        plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5),
        strip.placement = "outside",
        strip.background = element_blank())+
       # panel.spacing.y = unit(0, "lines")) +
png("AllBasins_FloodControl_Whiplash_March2023_222.png", units ="in", width=7, height=5, res = 300)
```

```{r}
write_csv(All_FloodRelease, "Floodflows_whiplash_May2023.csv")

write_csv(All_FloodRelease2, "Floodflows_Whiplash_Avg_May2023.csv")
1+1
```


```{r}
All_UncSpill <- list.files("C:/Users/gusta/Box/VICE Lab/RESEARCH/PROJECTS/CERC-WET/Task7_San_Joaquin_Model/pywr_models/results/Whiplash - 2023-03-13/", recursive=TRUE) %>%
 # grep("D2W1D2", ., value = TRUE) %>%
  #grep("merced", ., value = TRUE) %>%
  grep(#"Hydropower_Energy"
    "UncontrolledSpill_Flow_mcm.csv", ., value = TRUE)

head(All_UncSpill)
```

```{r}
filelist_UncSpill <- lapply(paste("C:/Users/gusta/Box/VICE Lab/RESEARCH/PROJECTS/CERC-WET/Task7_San_Joaquin_Model/pywr_models/results/Whiplash - 2023-03-13/",All_UncSpill,sep=""), read.csv)

#if necessary, assign names to data.frames
names(filelist_UncSpill) <- paste(All_UncSpill)
```


```{r}
filelist_UncSpill2<- invisible(lapply(names(filelist_UncSpill), function(x) assign(x,filelist_UncSpill[[x]][-c(1,2),]%>% 
                                                                   mutate(Sequence = substr(str_split(names(filelist_UncSpill[x]), "/")[[1]][3], 1,5), 
                                                                          Scenario = paste(substr(str_split(names(filelist_UncSpill[x]), "/")[[1]][3], 11,14), substr(str_split(names(filelist_UncSpill[x]), "/")[[1]][3], 11,12), sep=""),
                                                                          Number = substr(str_split(names(filelist_UncSpill[x]), "/")[[1]][3], 16,20),
                                                                          Basin = str_split(names(filelist_UncSpill[x]),"/")[[1]][1]),envir=.GlobalEnv))) 
head(filelist_UncSpill2)

```

```{r}
UncSpill_Mer <- filelist_UncSpill2 %>%
  lapply(., function(x) filter(x, Basin == "merced"))%>%
  do.call("rbind", .) %>%
  dplyr::select(., -contains(".1")) %>%
 # mutate(Total = rowSums(.[c(2:3)]))%>%
  #dplyr::select(node, Sequence, Scenario, Number,  Basin, Total) %>%
  reshape2::melt(., by = c("node", "Sequence", "Scenario", "Scenario2", "Scenario3", "Number", "Basin")) %>%
  mutate(node = as.Date(node, "%Y-%m-%d"))
UncSpill_Mer

UncSpill_Tuo <- filelist_UncSpill2 %>%
  lapply(., function(x) filter(x, Basin == "tuolumne"))%>%
  do.call("rbind", .) %>%
  dplyr::select(., -contains(".1")) %>%
 # mutate(Total = rowSums(.[c(2:5)]))%>%
#  dplyr::select(node, Sequence, Scenario, Number,  Basin, Total) %>%
  reshape2::melt(., by = c("node", "Sequence", "Scenario", "Scenario2", "Scenario3", "Number", "Basin")) %>%
  mutate(node = as.Date(node, "%Y-%m-%d"))
UncSpill_Tuo

UncSpill_Stn <- filelist_UncSpill2 %>%
  lapply(., function(x) filter(x, Basin == "stanislaus"))%>%
  do.call("rbind", .) %>%
  dplyr::select(., -contains(".1")) %>%
 # mutate(Total = rowSums(.[c(2:11)]))%>%
#  dplyr::select(node, Sequence, Scenario, Number,  Basin, Total) %>%
  reshape2::melt(., by = c("node", "Sequence", "Scenario", "Scenario2", "Scenario3", "Number", "Basin")) %>%
  mutate(node = as.Date(node, "%Y-%m-%d"))
UncSpill_Stn

UncSpill_USJ <- filelist_UncSpill2 %>%
  lapply(., function(x) filter(x, Basin == "upper_san_joaquin"))%>%
  do.call("rbind", .) %>%
  dplyr::select(., -contains(".1")) %>%
 # mutate(Total = rowSums(.[c(2:10)]))%>%
#  dplyr::select(node, Sequence, Scenario, Number,  Basin, Total) %>%
  reshape2::melt(., by = c("node", "Sequence", "Scenario", "Scenario2", "Scenario3", "Number", "Basin")) %>%
  mutate(node = as.Date(node, "%Y-%m-%d"))
UncSpill_USJ


All_UncSpill <- rbind(UncSpill_Mer, UncSpill_Tuo, UncSpill_Stn, UncSpill_USJ) %>%
  mutate(WaterYear = lfstat::water_year(node, origin = "usgs"),
         Count = ifelse(value > 0.01, 1, 0)) %>%
  group_by(WaterYear, Sequence, Scenario, Number, Basin, variable) %>%
  summarize(Count = sum(Count),
            Spill = sum(value))
All_UncSpill

All_FloodRelease$Spill <- All_UncSpill$Spill
All_FloodRelease$Count <- All_UncSpill$Count

All_UncSpill$variable <- factor(All_UncSpill$variable, levels = c("New.Melones.Lake.Flood.Control",  "Don.Pedro.Lake.Flood.Control","Exchequer.Dam.Flood.Release", "Millerton.Lake.Flood.Release"))
```


```{r}
All_FloodRelease2 <- All_FloodRelease %>%
group_by(Basin, Sequence, Scenario) %>%
  summarize(FloodRelease = mean(value),
            Spill = mean(Spill),
            Count = mean(Count)) %>%
                group_by(Basin, Scenario) %>%
            summarize(Mean_FloodRelease = mean(FloodRelease),
            Min_FloodRelease = min(FloodRelease),
            Max_FloodRelease = max(FloodRelease),
            Mean_Spill = mean(Spill),
            Min_Spill = min(Spill),
            Max_Spill = max(Spill),
            Mean_Count = mean(Count),
            Min_Count = min(Count),
            Max_Count = max(Count))
All_FloodRelease2
```

```{r}
ggplot(All_UncSpill) +
     theme_bw(base_size=12, base_family='Times New Roman') +
  geom_bar(aes(x= WaterYear, y=Count), stat = "identity") +
#ggthemes::scale_color_colorblind() +
   scale_y_continuous(expand = c(0, NA),
                      limits = c(0,NA)) +
  scale_x_discrete(breaks = c("1981", "1991", "2001", "2011", 
                              "1951", "1961", "1971"),
                    expand = c(0, NA))+
  facet_grid(variable~Scenario, scales = "free_x") +
  
  labs(#title = "Storage Below One Third of Reservoir Operating Capacity",
    #  subtitle = "RCP 8.5 Scenario",
       
  #  subtitle = "CanESM2",
    x = element_blank(),
       y = "Total Flood Control Releases\n(mcm/year)") +
 theme(#strip.text.x = element_blank(),
       #legend.title = element_blank(),
    #legend.position = "bottom",
     #   legend.direction = "horizontal",
      #  legend.box.margin = margin(t = -17),
        axis.text.x = element_text(angle = -40, vjust=-0.4),
        plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5),
        strip.placement = "outside",
        strip.background = element_blank())+
       # panel.spacing.y = unit(0, "lines")) +
png("AllBasins_FloodControl_whiplash_March2023_22.png", units ="in", width=20, height=15, res = 300)
```